### ISSUE TITLE
Possible updates? From Isla

### ISSUE THREAD

**Issue by Islaew** [ElliottMess/hisac#8]
- Assume the current inputs are to test it works? Unless i some how missed that steph saw orcas 
- Is it possible to split species by group as they are in the spread sheet? Each in its own drop down list - Would make it easier for people to find the species when inputting
- Maybe add the number of points each thing is worth on the drop down list? - ie Scallop - 4 points
- Is there a way of people being able to add their photos to it  or a way of adding who they saw it with? Would be cool to be able to have some photos at the end of it and makes people more honest 
- How do people add a new observation - ie not one currently on the list. If possible (I have no idea how hard any of this is to do) have it send the judge (me) an email with their proposed number of points for that sighting 
- How do I then add species to the list?

**Comment by ElliottMess** [comment]
@Islaew to answer your specific points:

- The current inputs are indeed just for tests.
- To add a new species, you can just add a new row to the google spreadsheet! I could add a form to do that, but it could be a bit complicated for something that can be done manually quite well and will not happen often really ( I think).

I am splitting the remaining issues into individual ones so that I can track their development better.

**Comment by Islaew** [comment]
Im happy to just add new species to the google sheet, wasnt sure if it was linked that way! Seems the easiest way to do it
